### ISSUE TITLE
Check for possible null pointer dereferences when using buffer->content

### ISSUE THREAD

**Issue by FSMaxB** [FSMaxB/molch#13]
Empty buffers have a null pointer as content. There might still be codepaths that allow for a dereference of such a null pointer to happen.

Find them and kill them with fire.

**Comment by tiagogehring** [comment]
A static analyzer (Clang for example comes with one) can usually catch those problems. I can have a look at it..

**Comment by FSMaxB** [comment]
Actually it doesn't. I use the clang static analyzer and it didn't catch it.
