### ISSUE TITLE
Theory on moving from AES to libsodium

### ISSUE THREAD

**Issue by Scratch-net** [FSMaxB/molch#41]
Hi and nice job you've done here!
I'm also looking forward to moving from AES to libsodium on axolotl and would like to find out about the theory on that. Is it safe to drop the HMAC and just use crypto_secretbox_easy instead of built in AES?

**Comment by FSMaxB** [comment]
I don't know anything about theory behind that. I'm not a cryptographer, I'm just implementing axolotl on top of libsodium.

What I do know, is that the axolotl protocol itself doesn't specify any particular type of cipher. It tells you what to do, once you have some kind of Diffie Hellman key exchange, symmetric encryption and an HMAC function. It doesn't specify which ones to use. I am building molch on the assumption, that it doesn't matter on which primitives axolotl is built on, as long as these primitives can be considered secure.

I'm not quite sure what you mean by "built in AES" and "dropp[ing] the HMAC". `crypto_secretbox_easy` does authentication by creating a MAC using Poly1305.

If by "moving from AES to libsodium", you mean using molch, I should note that, according to my current estimates, It might still take about half a year or longer until I would consider molch ready for production and I hope to get it reviewed by a cryptographer until then.

**Comment by Scratch-net** [comment]
Sorry for bringing you misunderstanding, I'm looking at TextSecure protocol which uses AES and stores HMAC separately. Now I understand that there's no difference between storing it separately and using it in crypto_box as you do.
